import "../globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import QueryProvider from "../components/QueryProvider";
import Bottombar from "../components/BottomBar";
import Sidebar from "../components/Sidebar";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Students System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-h-screen`}>
        <div className="flex flex-row">
          <Sidebar />
          <main className="flex-grow bg-[#121317]">
            <QueryProvider>{children}</QueryProvider>
          </main>
        </div>
        <Bottombar />
        <Toaster />
      </body>
    </html>
  );
}
